package com.healthcare.backend.reports.dto;

import com.healthcare.backend.reports.enums.ReportType;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;

@Getter
@Setter
public class ReportRequestDto {

    @NotBlank(message = "Report name is required")
    private String reportName;

    @NotNull(message = "Report type is required")
    private ReportType reportType;

    // JSON-encoded parameters used to generate the report (date range, filters, etc.)
    private String reportParameters;

    private String description;

    @NotNull(message = "Generated by staff member is required")
    private UUID generatedById;
}
