spring:
  application:
    name: backend

  datasource:
    password: Chathuka@9911
    username: root
    url: jdbc:mysql://localhost:3306/healthcare_erp
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:this-is-a-placeholder-secret-key-change-it-please-min-32-chars}
  expiration: 86400000